# Generated by Django 2.1 on 2018-08-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Person',
        ),
    ]
